manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
      
    - name: agilum
      url-base: https://github.com/agilum 
      
    - name: bluedrink9
      url-base: https://github.com/bluedrink9
      
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3.0
      import: app/west.yml 

    - name: zmk-caps-lock-led
      remote: agilum 
      revision: main 

    - name: zmk-layer-leds
      remote: agilum
      revision: main       
       
    - name: zmk-poor-mans-led-indicator
      remote: bluedrink9
      revision: main

  self:
    path: config

