manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
      
    - name: agilum
      url-base: https://github.com/agilum 
      
    - name: bluedrink9
      url-base: https://github.com/bluedrink9
      
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml 

    - name: zmk-caps-lock-led
      remote: agilum 
      revision: main 

    - name: layer-leds
      url: https://github.com/agilum/zmk-layer-leds
      revision: main
      path: modules/layer_leds        
       
    - name: zmk-poor-mans-led-indicator
      remote: bluedrink9
      revision: main

  self:
    path: config

